baseurl: https://ohdijkstra.github.io

DefaultContentLanguage: zh-cn

hasCJKLanguage: true

languages:
    en:
        languageName: English
        title: UWin AI
        weight: 1
        params:
            description: UWin AI
    zh-cn:
        languageName: ä¸­æ–‡
        title: UWin AI
        weight: 2
        params:
            description: UWin AI

[params]
  disqusShortname = "uwinai"

  sidebar:
        emoji: ğŸ˜„
        subtitle: è¡Œè‡³æ°´ç©·å¤„ï¼Œåçœ‹äº‘èµ·æ—¶ã€‚
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

menu:
    main: []

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/bw4uf
          params:
              icon: brand-github

